"""
Django settings for eduummah project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Adjust BASE_DIR to be the root of your Django project, not the entire application structure.
# This assumes your settings.py is within `backend/eduummah/eduummah`.
BASE_DIR = Path(__file__).resolve().parent.parent

print("Base directory:", BASE_DIR)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nhz)7el26^)h@ix#9&e^@g((=r=-8tx+61bt=jmk$yb1)is%vl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eduummah',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'eduummah.urls'

# Define the full path to the frontend build directory.
# Adjust if your project layout is different.

FRONTEND_BUILD_DIR = BASE_DIR.parent.parent / 'frontend' / 'build'


print("Frontend build directory:", FRONTEND_BUILD_DIR)
print("Static files directory:", FRONTEND_BUILD_DIR / 'static')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_BUILD_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eduummah.wsgi.application'

# Database configuration.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Ensure the path to db.sqlite3 is relative to your Django project.
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation.
AUTH_PASSWORD_VALIDATORS = [
    # ... your existing password validators ...
]

# Internationalization.
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images).
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    FRONTEND_BUILD_DIR / 'static',
]

# Default primary key field type.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Change from allowing all origins to specifying which origins are allowed.
CORS_ALLOW_ALL_ORIGINS = False  # Set this to False to disable the wildcard '*'

# Ensure this setting is set to True to allow cookies (credentials) to be included in cross-origin requests
CORS_ALLOW_CREDENTIALS = True


# Then specify the exact origins you want to allow
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Other CORS settings...
